### ISSUE TITLE
Добавить в конфиги возможность наследования

### ISSUE THREAD

**Issue by thefrol** [thefrol/powershell-yandexcloud-function-uploader#2]
Часто так получается, что большинство полей для `prod` и `dev` совпадают. Хочется в одном месте держать эти строки и менять лишь нужные, чтобы не запутаться

Так USER и PASS будет скорее всего одинаковым для DEV и прод, и если они поменяются могут возникнуть ошибки, или их нужно переписывать для каждого окружения. 

Если профили можно будет наследовать, то будем меньше ошибок в разработке, а это то, чего мы пытаемся достичь - помочь разработчику

```yaml
default: dev
profiles:
    dev~basic:
        function-name: bot-dev
    prod~basic:
        function-name: bot-prod
    basic:
        function-name: bot
        runtime: python311
        entrypoint: index.handler
        env:
            a:b
```

Так все переменные окружения будут совпадать и на деве и проде, при необходимости
